name: create target example
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - chackout main brench from github
        uses: actions/checkout@v1
      - name: step 2 - Set uo JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: step 3 - have github actions build maven project
       
      
      - name: step 4 - list the current directory
        run: ls -a
      - name: step 5 - what is the target folder
        run:
          cd target
          ls -a
